name: toy_village_app
description: "토이빌리지 모바일 앱입니다."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2951.0
  go_router: ^17.3.0
  flutter_material_design_icons: ^3.1.0+7447
  flutter_svg: ^2.3.0
  flutter_riverpod: ^3.3.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: WantedSans
      fonts:
        - asset: assets/font/WantedSans-Black.ttf
          weight: 900
        - asset: assets/font/WantedSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/WantedSans-Bold.ttf
          weight: 700
        - asset: assets/font/WantedSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/WantedSans-Medium.ttf
          weight: 500
        - asset: assets/font/WantedSans-Regular.ttf
          weight: 400

  assets:
    - assets/svg/